apiVersion: apps/v1
kind: Deployment
metadata:
  name: hr-frontend
  namespace: hr-system
  labels: { app: hr-frontend }
spec:
  replicas: 1
  selector:
    matchLabels: { app: hr-frontend }
  template:
    metadata:
      labels: { app: hr-frontend }
    spec:
      containers:
        - name: hr-frontend
          # replace with your image name/tag
          image: docker.io/tomfly2010/hr-frontend:staging-latest
          ports:
            - name: http
              containerPort: 8080
          readinessProbe:
            httpGet: { path: /, port: http }
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            httpGet: { path: /, port: http }
            initialDelaySeconds: 15
            periodSeconds: 10
