apiVersion: v1
kind: Service
metadata:
  name: hr-frontend
  namespace: hr-system
  labels: { app: hr-frontend }
spec:
  selector:
    app: hr-frontend
  ports:
    - name: http
      port: 80
      targetPort: 8080
  type: ClusterIP
