apiVersion: apps/v1
kind: Deployment
metadata:
  name: hr-backend
  labels: { app: hr-backend }
spec:
  selector:
    matchLabels: { app: hr-backend }
  template:
    metadata:
      labels: { app: hr-backend }
    spec:
      containers:
        - name: hr-backend
          image: tomfly2010/hr-backend:latest
          imagePullPolicy: IfNotPresent
          envFrom:
            - secretRef:
                name: hr-backend-secrets   # generated in overlay
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: staging              # overridden in prod overlay
          ports:
            - containerPort: 8080
