apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# leave namespace here so both overlays can inherit or override
namespace: hr-system

resources:
  - 00-configmap.yaml
  - 02-service.yaml
  - 03-deployment.yaml

commonLabels:
  app.kubernetes.io/name: hr-backend
  app.kubernetes.io/part-of: hr-system
