apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hr-ingress
  namespace: hr-system
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"
spec:
  ingressClassName: nginx
  rules:
    - host: hr.localtest.me
      http:
        paths:
          # expose Spring Boot actuator endpoints
          - path: /actuator
            pathType: Prefix
            backend:
              service:
                name: hr-backend
                port:
                  number: 8080

          # expose backend REST APIs
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: hr-backend
                port:
                  number: 8080

          # all other traffic goes to the Angular frontend
          - path: /
            pathType: Prefix
            backend:
              service:
                name: hr-frontend
                port:
                  number: 80
